<a href="https://colab.research.google.com/github/ProsperChuks/glowing-octo-waffle/blob/main/clw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

fov = np.ones((5,5), dtype='int')
fov[1:4,1:4]=0
fov[2,2]=9
print(fov)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [2]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
b = np.array([[11,12,13,14,15], [16,17,18,19,20]])
c = np.array([[21,22,23,24,25], [26,27,28,29,30]])

stacked = np.vstack([a,b,c])
print(stacked)
print(stacked[2:4,0:2])
print(stacked[[0,1,2,3], [1,2,3,4]])
print(stacked[[0], [3, 4]])
print(stacked[[0,4,5], 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[4 5]
[[ 4  5]
 [24 25]
 [29 30]]
