<a href="https://colab.research.google.com/github/ProsperChuks/glowing-octo-waffle/blob/main/numtut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
 
num = range(10)
for eachval in num:
  print(eachval+1)
 
a = np.array([1,2,3])
c = np.array([2,3,5])
 
ans = a * c
print(ans)

1
2
3
4
5
6
7
8
9
10
[ 2  6 15]


In [ ]:
# 2D
p = np.array([[1.0, 4.0, 3.0],[2.0, 9.0, 6.0]], dtype='float16')
print(p)
 
#get dimension
p.ndim

#get shape
p.shape

#get size
p.dtype

[[1. 4. 3.]
 [2. 9. 6.]]


dtype('float16')

In [ ]:
d = np.array([[2,5,6,0,1,9,4],[1,2,3,4,5,6,7]])
print(d)
#get a specific element [r, c]
d[0, -2]
#get a specific row
d[1,  :]
# #[startindex:endindex:stepsize]
d[0, 1:-1:2]

[[2 5 6 0 1 9 4]
 [1 2 3 4 5 6 7]]


array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#3d
h = np.array([[[4,5],[7,2]],[[9,1],[6,8]]])
h.ndim
print(h)

#getting a specific element (work outside in)
h[1, 1, 1]

[[[4 5]
  [7 2]]

 [[9 1]
  [6 8]]]


(2, 2, 2)

Initializing Different types of Arrays

In [ ]:
# all 0s matrix
np.zeros((2,3,3), dtype='int16')

# all 1s matrix
np.ones((2,2,2), dtype='int32')

# any other number
np.full((2,2), 78)

# any other number (full_like)
np.full_like(h, 3)

# random decimal numbers
np.random.rand(4,2)
np.random.random_sample(h.shape)
np.random.randint(8, size=(h.shape))

# identity matrix
np.identity(5)

# repeat an array
arr = np.array([[1,3,9]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 3 9]
 [1 3 9]
 [1 3 9]]


Mathematical Calculations

In [ ]:
a = np.array([45, 45, 45])

np.cos(a)
np.tan(a)
np.sin(a)

array([1.61977519, 1.61977519, 1.61977519])

Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)
# matrix multiply function
np.matmul(a,b)

# find the determinant
c = np.identity(3)
np.linalg.det(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


1.0

Statistics

In [ ]:
stats = np.array([[8,7,2], [3,4,6]])
print(stats)

# getting the min
np.min(stats)

# getting the max
np.max(stats)

np.sum(stats)

[[8 7 2]
 [3 4 6]]


30

Re-organizing arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8,]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
stacked = np.vstack([v2,v1])

np.vsplit(stacked, 2)

[array([[5, 6, 7, 8]]), array([[1, 2, 3, 4]])]

# **Miscellaneous**
### load data from file

In [ ]:
link = "/content/drive/MyDrive/Colab Notebooks/data.txt"
filedata = np.genfromtxt(link, dtype='int16', delimiter=',')
print(filedata)

[[  1  62  24  52 495  59   8   4   7   1   0   2  62  13  27  60  21  11]
 [  4  69  43  56 712  81   9  47  15   6   8   0  14  56  97  74  31  12]
 [  1  13  44  14 444  33   2   8   1   7   5   8   9   6   3  98  23  49]]


### Boolean Masking and Advanced Indexing

In [ ]:
print(filedata[filedata > 50])

(~((filedata > 50) & (filedata < 100)))

[ 62  52 495  59  62  60  69  56 712  81  56  97  74 444  98]


array([[ True, False,  True, False,  True, False,  True,  True,  True,
         True,  True,  True, False,  True,  True, False,  True,  True],
       [ True, False,  True, False,  True, False,  True,  True,  True,
         True,  True,  True,  True, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True]])